namespace: "%namespace%"
environment: '%environment%'

image:
    tag: spryker/php:${PHP_VERSION:-8.2}

regions:
    GLOBAL:
        services:
            database:
                database: '%database.name%'
                username: '%database.user%'
                password: '%database.password%'

        stores:
            GLOBAL:
                services:

groups:
    GLOBAL:
        region: GLOBAL
        applications:
            Glue:
                application: glue-backend
                endpoints:
                    '%hosts.glue%':
                        store: GLOBAL
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "%database.root_password%"
        endpoints:
            localhost:3306:
                protocol: tcp
