imports:
    deploy.base.template.yml:

tag: 'dev'

# our template contains configuration that only applies if using this environment name
# see config/Shared/config_default-docker.dev.php
environment: docker.dev

image:
    php:
        ini:
            "opcache.enable_cli": 0
            "opcache.enable": 0
    environment:
        SPRYKER_GLUE_BACKEND_HOST: '%hosts.glue%'
        SPRYKER_BE_HOST: '%hosts.backoffice%'
        SPRYKER_AOP_INFRASTRUCTURE: '{}'

        AOP_APP_IDENTIFIER: "" # spryker/message-broker
        AWS_DEFAULT_REGION: eu-central-1

        SPRYKER_MESSAGE_BROKER_HTTP_CHANNEL_SENDER_BASE_URL: "%message_broker.http_sender.base_url%"
        SPRYKER_MESSAGE_BROKER_HTTP_CHANNEL_RECEIVER_BASE_URL: "%message_broker.http_receiver.base_url%"
        SPRYKER_REGISTRY_URL: "%http_registry.base_url%"
composer:
    mode: ''
    autoload: ''

assets:
    mode: development

services:
    dashboard:
        engine: dashboard
        endpoints:
            spryker.local:

docker:
    ssl:
        enabled: false
        redirect: true

    testing:
        store: GLOBAL

    debug:
        enabled: true
        xdebug:
            enabled: true

    mount:
        native:
            platforms:
                - linux

        docker-sync:
            platforms:
                - windows

        mutagen:
            platforms:
                - macos
