namespace: "%namespace%"
environment: '%environment%'

image:
    tag: spryker/php:${PHP_VERSION:-8.3}
    environment:
        SPRYKER_GLUE_BACKEND_HOST: '%hosts.glue%'
        SPRYKER_BE_HOST: '%hosts.backoffice%'
        SPRYKER_AOP_INFRASTRUCTURE: '{
            "SPRYKER_MESSAGE_BROKER_HTTP_SENDER_CONFIG": {
              "endpoint": "%message_broker.http_sender.endpoint%"
            },
            "SPRYKER_MESSAGE_BROKER_SQS_RECEIVER_CONFIG": {
              "default": {
                  "endpoint": "%message_broker.sqs_receiver.endpoint%",
                  "auto_setup":false,
                  "buffer_size":1,
                  "queue_name":"%message_broker.sqs_receiver.queue_name%",
                  "poll_timeout":10
              }
            }
        }'

        AOP_APP_IDENTIFIER: "" # spryker/message-broker: AppIdentifierMessageAttributeProviderPlugin
        AWS_DEFAULT_REGION: eu-central-1

        SPRYKER_MESSAGE_BROKER_HTTP_CHANNEL_SENDER_BASE_URL: "%message_broker.http_sender.base_url%"
        SPRYKER_MESSAGE_BROKER_HTTP_CHANNEL_RECEIVER_BASE_URL: "%message_broker.http_receiver.base_url%"
        SPRYKER_REGISTRY_URL: "%http_registry.base_url%"

    node:
        version: 18
        npm: 9

regions:
    GLOBAL:
        services:
            database:
                database: '%database%'
                username: spryker
                password: secret

        stores:
            GLOBAL:
                services:

groups:
    GLOBAL:
        region: GLOBAL
        applications:
            Glue:
                application: glue-backend
                endpoints:
                    '%hosts.glue%':
                        store: GLOBAL
            Backoffice:
                application: backoffice
                endpoints:
                    '%hosts.backoffice%':
                        store: GLOBAL
services:
    database:
        engine: mysql
        version: mariadb-10.5
        root:
            username: "root"
            password: "secret"
        endpoints:
            localhost:3306:
                protocol: tcp

    scheduler:
        engine: jenkins
        version: '2.324'
        endpoints:
            '%hosts.scheduler%':
