imports:
    deploy.base.template.yml:

tag: '1.0'

image:
    environment:
        SPRYKER_HOOK_BEFORE_DEPLOY: "vendor/bin/install -r pre-deploy -vvv"
        SPRYKER_HOOK_AFTER_DEPLOY: "vendor/bin/install -r post-deploy -vvv"
        SPRYKER_HOOK_INSTALL: "vendor/bin/install -r production --no-ansi -vvv"
        SPRYKER_HOOK_DESTRUCTIVE_INSTALL: "vendor/bin/install -r destructive --no-ansi -vvv"
        SPRYKER_REGISTRY_URL: "%http_registry.base_url%"

    php:
        ini:
            opcache.interned_strings_buffer: 32
        enabled-extensions:
            - newrelic

composer:
    mode: --no-dev
    autoload: --classmap-authoritative

assets:
    image: fholzer/nginx-brotli:v1.18.0
    mode: production
    compression:
        brotli:
            static: only
        gzip:
            static: true
            level: 5

docker:
    ssl:
        enabled: true
    testing:
        store: GLOBAL
    debug:
        enabled: false
    mount:
        baked:
