name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform-image: [
            'spryker/php:7.4',
            'spryker/php:8.1-RC'
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker
        env:
            SPRYKER_PLATFORM_IMAGE: ${{ matrix.platform-image }}
        run: |
            git clone -b bugfix/php-warnings https://github.com/spryker/docker-sdk docker
            docker/sdk boot deploy.ci.yml
            docker/sdk up

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Check PHP for syntax errors
        run: find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

      - name: CodeStyle Checks
        run: composer cs-check

      - name: PHPStan Checks
        run: composer stan

      - name: Run tests
        run: |
            vendor/bin/codecept build
            vendor/bin/codecept run --coverage-xml

      - name: Code Coverage Report
        if: success() && matrix.platform-image == 'spryker/php:8.1-RC'
        uses: codecov/codecov-action@v2
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./tests/_output/coverage.xml
            version: "v0.1.15"
