name: CI

on:
    pull_request:
    push:
        branches:
            - main
            - develop
    workflow_dispatch:

jobs:
    validation:
        name: "CS, PHPStan, Security, App validation"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '8.3'

        env:
            APPLICATION_ENV: docker.dev
            APPLICATION_STORE: GLOBAL

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Configure sysctl limits
                run: |
                    sudo swapoff -a
                    sudo sysctl -w vm.swappiness=1
                    sudo sysctl -w fs.file-max=262144
                    sudo sysctl -w vm.max_map_count=262144

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, intl, pdo_mysql

            -   name: Composer get cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Composer Cache
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Composer validate
                run: composer validate

            -   name: Composer version
                run: composer --version

            -   name: Composer Install
                run: composer install --no-interaction -o

            -   name: Generate transfer objects
                run: vendor/bin/console transfer:generate

            -   name: Generate transfer databuilder objects
                run: vendor/bin/console transfer:databuilder:generate

            -   name: Propel install
                run: |
                    vendor/bin/console propel:schema:copy
                    vendor/bin/console propel:model:build
                    vendor/bin/console transfer:entity:generate

            -   name: Codecept build
                run: vendor/bin/codecept build --ansi

            -   name: Generate autocompletion files
                run: vendor/bin/console dev:ide-auto-completion:generate

            -   name: Check PHP for syntax errors
                run: find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

            -   name: Validate propel files
                run: |
                    vendor/bin/console propel:schema:validate
                    vendor/bin/console propel:schema:validate-xml-names

            -   name: Validate transfer files
                run: vendor/bin/console transfer:validate

            -   name: Run Rector checks
                run: composer rector-ci

            -   name: Run CodeStyle checks
                run: vendor/bin/phpcs -p

            -   name: Run PHPStan
                run: vendor/bin/phpstan analyze

            -   name: Run Security check
                run: vendor/bin/console security:check

            -   name: Validate App
                run: vendor/bin/acp app:validate

    mariadb-alpine:
        name: "MariaDB / Alpine / Tests / Mutation Tests"
        strategy:
            matrix:
                php-version:
                    - '8.2'

        runs-on: ubuntu-latest
        env:
            PROGRESS_TYPE: plain
            PHP_VERSION: ${{ matrix.php-version }}

        steps:
            -   uses: actions/checkout@v4

            -   name: Install apt-packages
                run: |
                    sudo apt install -y libxml2-utils

            -   name: Install docker-compose
                run: |
                    sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose

            -   name: Run project in Docker
                run: |
                    git clone https://github.com/spryker/docker-sdk.git ./docker
                    docker/sdk boot deploy.dev.yml -v
                    docker/sdk up -t -v --data --build

            -   name: Run tests with coverage
                if: success()
                run: |
                    docker/sdk testing composer test-cover
                    docker/sdk testing composer test-strict-ci

            -   name: Check installed commands
                run: |
                    which xmllint || echo "xmllint not found"
                    which grep || echo "grep not found"
                    which awk || echo "awk not found"
